name:                algebra-checkers
version:             0.1.0.0
github:              "isovector/algebra-checkers"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2020 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Model and test API surfaces algebraically
category:            Model

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/algebra-checkers#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.12.0.0 && < 3
- containers >= 0.5.10.2
- syb >= 0.7
- QuickCheck >= 2.10.1 && < 3
- transformers >= 0.5.2.0
- mtl >= 2.2.2 && < 3
- pretty >= 1.1.3.3 && < 2
- ansi-terminal >= 0.10.3
- th-instance-reification >= 0.1.5.1
- groups >= 0.4.1.0
- checkers >= 0.5.5
- th-tc
- th-abstraction
- haskell-lexer
- parsec
- string-interpolate

ghc-options:
  - -Wall

executables:
  algebra-check:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebra-checkers

library:
  source-dirs: src
  # other-modules:
  #   - AlgebraCheckers.Homos
  #   - AlgebraCheckers.Patterns
  #   - AlgebraCheckers.Ppr
  #   - AlgebraCheckers.Suggestions
  #   - AlgebraCheckers.Theorems
  #   - AlgebraCheckers.TH
  #   - AlgebraCheckers.Types
  #   - AlgebraCheckers.Unification

tests:
  polysemy-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - algebra-check
    build-tool-depends:
    - algebra-checkers
    dependencies:
    - algebra-checkers
    - hspec
    - QuickCheck

