name:                algebra-checkers
version:             0.1.0.0
github:              "isovector/algebra-checkers"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2020 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/algebra-checkers#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- containers
- syb
- checkers
- QuickCheck
- transformers
- mtl

library:
  source-dirs: src

